---
- name: Criar usu치rio administrador no Windows
  hosts: windows
  tasks:
    - name: Criar usu치rio 'iac'
      ansible.windows.win_user:
        name: 'iac'
        password: 'Senha super segura'  
        description: 'Usu치rio criado via Ansible'
        state: present
      ignore_errors: yes

    - name: Adicionar usu치rio 'iac' ao grupo Administradores
      ansible.windows.win_group_membership:
        name: Administradores
        members:
          - 'iac'
        state: present
      ignore_errors: yes
  become_user: TI