---
- name: Criar usu치rio administrador no Windows
  hosts: windows
  tasks:
    - name: Criar usu치rio 'iac'
      ansible.windows.win_user:
        name: iac
        password: 'SenhaForte'  
        description: 'Usu치rio criado via Ansible'
        state: present

    - name: Adicionar usu치rio 'iac' ao grupo Administradores
      ansible.windows.win_group_membership:
        name: Administradores
        members:
          - iac
        state: present
